name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      working-directory: lambda-source
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build coverage file
      working-directory: lambda-source
      run: |
        pytest --junitxml=pytest.xml test_cloudtrail_cis_notifier.py | tee pytest-coverage.txt

    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        junitxml-path: lambda-source/pytest.xml
