name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.9

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      working-directory: lambda-source
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: lambda-source
      run: |
        pytest --junitxml=pytest.xml test_cloudtrail_cis_notifier.py

    - name: Pytest comment
      if: success() || failure()    # run this step even if previous step failed
      uses: MishaKav/pytest-coverage-comment@main
      with:
        junitxml-path: lambda-source/pytest.xml

  security:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./lambda-source/requirements.txt
          npm install --no-fund snyk -g
      - name: Run Snyk to check for vulnerabilities
        run: |
          snyk test --org=$ORG --file=./lambda-source/requirements.txt
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            ORG: broadwing-limited
