name: Workflow for Python using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python: ["3.10"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./lambda-source/requirements.txt
          npm install --no-fund snyk -g
      - name: Run Snyk to check for vulnerabilities
        run: |
          snyk test --org=$ORG --file=./lambda-source/requirements.txt
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            ORG: broadwing-limited
